# Generated by Django 4.0 on 2021-12-29 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_project_date_tasks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='date',
        ),
    ]
