# Generated by Django 4.0 on 2021-12-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasks',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='due_date',
        ),
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
